import type { Product, Source } from './types';

const reviewed = '2026-09-13';
const label = (id:string, title:string, url:string, note:string, section='Dosage forms / Description; Clinical pharmacology'):Source => ({id,title,url,section,reviewed,note});
const dm = (setId:string) => `https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=${setId}`;

// Label presence, FDA approval, present marketing and pharmacy stock are different facts.
// Evidence describes the implemented model, not the existence of product-specific evidence.
export const sources:Source[] = [
  label('S1','Concerta — FDA prescribing information, February 2026','https://www.accessdata.fda.gov/drugsatfda_docs/label/2026/021121s34s40s45lbl.pdf','Figure 1 is a group mean after one 18 mg dose. The reconstructed trace and estimated terminal tail have different provenance. Dose scaling is an approximation.','§§12.2–12.3; Figure 1; Table 7; §3'),
  label('S2','Ritalin IR — DailyMed prescribing information',dm('c0bf0835-6a2f-4067-a158-8b86c4b0668a'),'10 mg reference: approximate Cmax 4.3 ± 2.3 ng/mL and average Tmax 2 h. The application curve is a constructed model, not published raw data.','§§3, 12.3'),
  label('S3','Ritalin LA — FDA prescribing information, 2025','https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/021284s050lbl.pdf','Adult Ritalin-tablet half-life about 3.5 h (range 1.3–7.7 h); the LA two-pulse formulation needs its own model.','§§3, 12.3; Figure 1; Table 4'),
  label('S4','Adderall XR / Vyvanse / Mydayis — FDA labels, April 2026','https://www.accessdata.fda.gov/drugsatfda_docs/label/2026/021303s040,021977s052,208510s009,022063s007lbl.pdf','Multi-product document. Select the correct product section. d- and l-amphetamine must remain distinct analytes.','Each product: §§3, 12.3'),
  label('S5','Vyvanse — FDA prescribing information, 2025','https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/021977s054,208510s011lbl.pdf','Capsules and chewables are distinct formulations. Package lisdexamfetamine dimesylate mg is not dextroamphetamine mg.','§§3, 11–12.3'),
  label('S6','Focalin XR — FDA prescribing information, 2025','https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/021802s045lbl.pdf','Dexmethylphenidate is the d-enantiomer. The two-release-component profile cannot be replaced by a racemic IR model.'),
  label('S7','Jornay PM — FDA prescribing information, September 2025','https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/209311s013lbl.pdf','Evening delayed release crosses midnight; in the adult 100 mg study median Tmax was 14 hours after dosing.'),
  label('S8','Azstarys — DailyMed prescribing information',dm('00b5e716-5564-4bbd-acaf-df2bc45a5663'),'Prescribing information revised September 2025; listing updated May 2026. Supersedes the brief’s 2023 label for current reference. Preserve both labeled ingredient amounts.'),
  label('S9','Xelstrym — DailyMed prescribing information',dm('0862f02a-72a8-41cc-8845-57cf4974bb6f'),'Record application and removal. Strength is labeled delivery over 9 hours, not total drug loaded in the patch.'),
  label('S10','Strattera / atomoxetine — DailyMed reference label',dm('309de576-c318-404a-bc15-660c2b1876fb'),'Historical brand reference. CYP2D6 status and inhibitors materially change exposure. Current generic labeler and marketing require separate confirmation.'),
  label('S11','Qelbree — FDA prescribing information, January 2025','https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/211964s013lbl.pdf','Viloxazine ER has its own PK and clinical evidence. A daily plasma peak does not establish an immediate focus window.'),
  label('S12','Onyda XR — FDA prescribing information, June 2024','https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/217645s001lbl.pdf','Extended-release oral suspension, 0.1 mg clonidine hydrochloride/mL. Not interchangeable mg-for-mg with other clonidine formulations.'),
  label('S13','Arynta — FDA prescribing information, 2025','https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219847s000lbl.pdf','Oral solution contains 10 mg lisdexamfetamine dimesylate/mL. Preserve salt strength and mL; do not silently convert to active dextroamphetamine.'),
  label('S14','Simtriyo — FDA prescribing information, July 2026','https://www.accessdata.fda.gov/drugsatfda_docs/label/2026/218145s000lbl.pdf','FDA labels centanafadine a CNS stimulant. Exposure is slightly greater than dose proportional; no linear concentration scaling is implemented.'),
  label('S15','FDA novel drug approvals, 2026','https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2026','Lists Simtriyo (centanafadine), ADHD approval July 24, 2026. Approval does not establish pharmacy availability.','Approval table'),
  label('S16','IQVIA stimulant trends report — DEA-hosted historical survey','https://www.deadiversion.usdoj.gov/pubs/docs/IQVIA-Report-on-Stimulant-Trends-2024.pdf','Historical discovery checklist; not proof that each named product is currently marketed.','Appendices 2–3'),
  label('S17','FDA Orange Book','https://www.fda.gov/drugs/drug-approvals-and-databases/approved-drug-products-therapeutic-equivalence-evaluations-orange-book','Approved product, formulation and therapeutic-equivalence discovery. A product must be reconciled separately from its model.','Approved-product discovery'),
  label('S18','NLM DailyMed SPL API documentation','https://dailymed.nlm.nih.gov/dailymed/webservices-help/v2/spls_api.cfm','Structured source discovery; label updates must undergo review before replacing a pinned model.','SPL API'),
  label('S19','NICE NG87 — ADHD diagnosis and management','https://www.nice.org.uk/guidance/ng87/chapter/recommendations','Supports monitoring sleep, weight, pulse and blood pressure. Verified in the indexed official recommendations after direct retrieval failed; not numerical PK evidence.','§§1.8.5, 1.8.9, 1.8.17'),
  label('C1','Methylin oral solution — DailyMed',dm('9e3c22d9-71d9-46a7-b315-8021c94c4bec'),'Distinct 5 mg/5 mL and 10 mg/5 mL solutions; confirm the bottle concentration.'),
  label('C2','Methylphenidate IR chewable tablets — DailyMed',dm('e5cb0740-813f-4dce-8c29-d7680c66e77c'),'2.5, 5 and 10 mg chewable tablet family; exact generic labeler must be confirmed.'),
  label('C3','Relexxii — DailyMed',dm('22d5fa47-b5b9-4fd9-980c-4eb88e95ae5d'),'18, 27, 36, 45, 54, 63 and 72 mg ER tablets. No automatic substitution of the Concerta model.'),
  label('C4','Aptensio XR — DailyMed',dm('5adedc01-ebf0-11e3-ac10-0800200c9a66'),'10, 15, 20, 30, 40, 50 and 60 mg extended-release capsules.'),
  label('C5','Metadate CD — DailyMed',dm('29f06562-6b6a-4ca6-b62e-d08a45fb3dd4'),'10, 20, 30, 40, 50 and 60 mg extended-release capsules; formulation uses different release fractions from Ritalin LA.'),
  label('C6','Quillivant XR — DailyMed',dm('c2dc2109-44a6-4797-b04e-18761dd9d45a'),'Reconstituted extended-release suspension: equivalent to 25 mg methylphenidate HCl/5 mL. Powder is not an administration-ready liquid.'),
  label('C7','QuilliChew ER — DailyMed',dm('defc1205-8e90-4b1e-b862-05e4c35c7364'),'20 and 30 mg tablets are functionally scored and can be halved. 40 mg is unscored and cannot be divided.'),
  label('C8','Cotempla XR-ODT — DailyMed',dm('33f70f58-c871-42c8-8adb-345caeafefcd'),'8.6, 17.3 and 25.9 mg are methylphenidate base strengths. Preserve this basis in records.'),
  label('C9','Daytrana — DailyMed',dm('2c312c31-3198-4775-91ab-294e0b4b9e7f'),'Transdermal exposure depends on wear duration and patch size. Repeat-dose carryover and absorption after removal need specific modeling.'),
  label('C10','Focalin IR — DailyMed',dm('2016f5c2-95d2-4655-af65-c588c2bf5e6d'),'2.5, 5 and 10 mg dexmethylphenidate HCl tablets. Distinct from racemic methylphenidate.'),
  label('C11','Adderall IR — DailyMed',dm('f22635fe-821d-4cde-aa12-419f8b53db81'),'5, 7.5, 10, 12.5, 15, 20 and 30 mg tablets. Four salt amounts form the labeled total; no base-equivalence conversion is performed.'),
  label('C12','Evekeo — DailyMed',dm('f469fb38-0380-4621-9db3-a4f429126156'),'Amphetamine sulfate tablets, 5 and 10 mg. Do not treat the enantiomer ratio as identical to Adderall.'),
  label('C13','Evekeo ODT — DailyMed','https://dailymed.nlm.nih.gov/dailymed/downloadpdffile.cfm?setId=1e25f905-6c0b-4b19-a3b6-b2a386afa1c3','5, 10, 15 and 20 mg amphetamine sulfate orally disintegrating tablets.'),
  label('C14','Dyanavel XR — DailyMed',dm('ae304b29-0b40-40ec-ad0d-76b742d4a9b9'),'Separate 2.5 mg/mL ER suspension and 5, 10, 15, 20 mg ER tablets. Labeled strengths use amphetamine base.'),
  label('C15','Adzenys XR-ODT — DailyMed',dm('c1179269-00b5-48ea-972d-31e614e99b7e'),'3.1, 6.3, 9.4, 12.5, 15.7 and 18.8 mg amphetamine base. Different labeled strength basis from mixed amphetamine salts.'),
  label('C16','Zenzedi — DailyMed',dm('d6394df5-f2c9-47eb-b57e-f3e9cfd94f84'),'Dextroamphetamine sulfate IR tablets: 2.5, 5, 7.5, 10, 15, 20 and 30 mg.'),
  label('C17','ProCentra — DailyMed',dm('1548cce2-fb6b-4f17-8a3b-868933f6c9d6'),'5 mg dextroamphetamine sulfate/5 mL oral solution. Record mL and bottle strength.'),
  label('C18','Dexedrine Spansule — DailyMed',dm('cc717b9b-22ea-4c60-a1d4-ee38a40bce78'),'Dextroamphetamine sulfate sustained-release capsules. Label strengths are not a stock or marketing guarantee.'),
  label('C19','Desoxyn — DailyMed','https://dailymed.nlm.nih.gov/dailymed/downloadpdffile.cfm?setId=81bfc45f-c345-47d0-9fc9-77abe553b541','Methamphetamine HCl 5 mg oral tablets; availability and current package labeler unverified.'),
  label('C20','Intuniv — DailyMed',dm('b972af81-3a37-40be-9fe1-3ddf59852528'),'1, 2, 3 and 4 mg guanfacine ER tablets. IR and ER exposure differs; no mg-for-mg model substitution.'),
  label('C21','Clonidine HCl ER tablets — DailyMed',dm('0100c70d-7fde-46a1-8374-940550a27e43'),'0.1 mg unscored ER tablets; ADHD formulation associated with Kapvay. Other clonidine ER products may have different indications.'),
  label('C22','Metformin hydrochloride IR tablets — DailyMed',dm('b8004451-7b26-425b-b5ea-cbb1b08e30e3'),'Immediate-release tablets: 500, 850 and 1000 mg metformin hydrochloride. Indicated for type 2 diabetes, not ADHD. No product-specific model is implemented.','§§1, 3, 11, 16'),
  label('C23','Metformin hydrochloride ER tablets, 500 / 750 mg — DailyMed',dm('6d6ee6f8-9650-ff4f-e053-2991aa0acf19'),'This conventional ER label lists 500 and 750 mg metformin hydrochloride. Keep separate from the osmotic ER family.','§§1, 3, 11, 16; RxNorm'),
  label('C24','Metformin hydrochloride osmotic ER tablets, 500 / 1000 mg — DailyMed',dm('ef77c7dd-a65f-4adc-a0d9-a93779b459a0'),'500 and 1000 mg metformin hydrochloride; DailyMed RxNorm mapping identifies osmotic 24-hour ER tablets. No mg-for-mg curve transfer from another formulation.','§§1, 3, 16; RxNorm'),
  label('C25','Riomet metformin hydrochloride oral solution — DailyMed historical label',dm('05d4df4b-dfe8-4828-b423-a3d4f2c4114a'),'Historical December 2018 label: 500 mg per 5 mL (100 mg/mL) metformin hydrochloride solution. Current package labeler and marketing are unverified; this is not an ER suspension.','§§1, 3, 11, 16'),
  label('C26','Dextroamphetamine sulfate IR tablets — DailyMed, Winder reference',dm('ca1a8890-0675-4c9c-9716-6c28f975d827'),'Winder label updated June 18, 2025 lists 2.5, 5, 7.5, 10, 15, 20 and 30 mg tablets and individual package NDCs. This supports the generic formulation catalog, not the user’s manufacturer, current availability or a concentration model. Scoring differs by strength.','Description; How Supplied; Product information'),
];

const unverified = 'Label referenced; current marketing and stock unverified';
const assumedNote = 'No product-specific model is implemented. An illustration requires explicitly accepted assumptions; it is not a prediction of this medicine.';
function product(id:string,name:string,generic:string,formulation:string,family:string,strengths:string[],sourceIds:string[],extra:Partial<Product>={}):Product {
  return {id,name,generic,formulation,family,strengths,sourceIds,unit:'tablet',strengthUnit:'mg',manufacturer:'Confirm labeler on package',evidence:'D',model:'assumption',route:'oral',status:unverified,note:assumedNote,...extra};
}

export const products:Product[] = [
  product('ritalin','Ritalin IR','methylphenidate hydrochloride','Immediate-release tablet','Methylphenidate',['5','10','20'],['S2','S3'],{evidence:'B',model:'ritalin',referenceDose:10,note:'Constructed adult reference: 10 mg, Cmax 4.3 ng/mL, Tmax 2 h, half-life 3.5 h. Other amounts remain loggable and require explicit dimensionless assumptions; no individual drug levels are predicted.'}),
  product('methylphenidate-ir','Methylphenidate IR (generic)','methylphenidate hydrochloride','Immediate-release tablet','Methylphenidate',['5','10','20'],['S2'],{note:'Generic family entry: confirm the exact manufacturer and label. No automatic model transfer from the Ritalin reference.'}),
  product('methylin-solution','Methylin oral solution','methylphenidate hydrochloride','Immediate-release oral solution','Methylphenidate',['1','2'],['C1'],{unit:'mL',strengthUnit:'mg/mL',note:'Select the bottle concentration: 1 mg/mL (5 mg/5 mL) or 2 mg/mL (10 mg/5 mL). '+assumedNote}),
  product('methylphenidate-chewable','Methylphenidate chewable (generic)','methylphenidate hydrochloride','Immediate-release chewable tablet','Methylphenidate',['2.5','5','10'],['C2']),
  product('concerta','Concerta','methylphenidate hydrochloride','Osmotic extended-release tablet','Methylphenidate',['18','27','36','54'],['S1'],{evidence:'A',model:'concerta',referenceDose:18,note:'18 mg group-mean reconstruction. A separate estimated tail extends beyond the published trace. Scaling and mixed-product sums add assumptions. Swallow whole; do not split, crush or chew.'}),
  product('relexxii','Relexxii','methylphenidate hydrochloride','Extended-release tablet','Methylphenidate',['18','27','36','45','54','63','72'],['C3'],{note:'Do not split, crush or chew. Its label includes reference data from another ER formulation; the Concerta curve is not automatically assigned. '+assumedNote}),
  product('ritalin-la','Ritalin LA','methylphenidate hydrochloride','Extended-release bead capsule','Methylphenidate',['10','20','30','40'],['S3'],{unit:'capsule'}),
  product('aptensio-xr','Aptensio XR','methylphenidate hydrochloride','Extended-release bead capsule','Methylphenidate',['10','15','20','30','40','50','60'],['C4'],{unit:'capsule'}),
  product('metadate-cd','Metadate CD','methylphenidate hydrochloride','Extended-release CD capsule','Methylphenidate',['10','20','30','40','50','60'],['C5'],{unit:'capsule'}),
  product('quillivant-xr','Quillivant XR','methylphenidate hydrochloride equivalent','Extended-release oral suspension','Methylphenidate',['5'],['C6'],{unit:'mL',strengthUnit:'mg/mL',note:'After pharmacist reconstitution: 25 mg/5 mL (5 mg/mL). Record administered liquid volume. '+assumedNote}),
  product('quillichew-er','QuilliChew ER','methylphenidate hydrochloride equivalent','Extended-release chewable tablet','Methylphenidate',['20','30','40'],['C7'],{note:'20 and 30 mg tablets can be halved as labeled. The 40 mg tablet cannot be divided. '+assumedNote}),
  product('cotempla-xr-odt','Cotempla XR-ODT','methylphenidate base','Extended-release orally disintegrating tablet','Methylphenidate',['8.6','17.3','25.9'],['C8'],{note:'Strength is methylphenidate base; it is not the hydrochloride strength used on many other packages. '+assumedNote}),
  product('jornay-pm','Jornay PM','methylphenidate hydrochloride','Delayed-release / extended-release capsule','Methylphenidate',['20','40','60','80','100'],['S7'],{unit:'capsule',note:'Product-specific delayed absorption can begin the next day. No generic morning-release PK model is assigned. '+assumedNote}),
  product('daytrana','Daytrana','methylphenidate','Transdermal system','Methylphenidate',['10','15','20','30'],['C9'],{unit:'patch',strengthUnit:'mg/9 h',route:'transdermal',note:'Labeled delivery over 9 hours, not total patch drug content or measured absorption. Record application and removal. '+assumedNote}),
  product('focalin','Focalin IR','dexmethylphenidate hydrochloride','Immediate-release tablet','Dexmethylphenidate',['2.5','5','10'],['C10']),
  product('focalin-xr','Focalin XR','dexmethylphenidate hydrochloride','Extended-release bead capsule','Dexmethylphenidate',['5','10','15','20','25','30','35','40'],['S6'],{unit:'capsule'}),
  product('dexmethylphenidate-ir','Dexmethylphenidate IR (generic)','dexmethylphenidate hydrochloride','Immediate-release tablet','Dexmethylphenidate',['2.5','5','10'],['C10']),
  product('dexmethylphenidate-er','Dexmethylphenidate ER (generic)','dexmethylphenidate hydrochloride','Extended-release capsule','Dexmethylphenidate',['5','10','15','20','25','30','35','40'],['S6'],{unit:'capsule'}),
  product('azstarys','Azstarys','serdexmethylphenidate / dexmethylphenidate','Prodrug / immediate-release combination capsule','Dexmethylphenidate',['26.1/5.2','39.2/7.8','52.3/10.4'],['S8'],{unit:'capsule',ingredients:[{name:'serdexmethylphenidate',ratio:1},{name:'dexmethylphenidate',ratio:1}],note:'Two package amounts, in order: serdexmethylphenidate / dexmethylphenidate. Preserve both; do not count converted active drug twice or convert mg-for-mg from other products. '+assumedNote}),
  product('adderall-ir','Adderall IR','mixed amphetamine salts','Immediate-release tablet','Amphetamine',['5','7.5','10','12.5','15','20','30'],['C11'],{ingredients:[{name:'dextroamphetamine saccharate',ratio:.25},{name:'amphetamine aspartate monohydrate',ratio:.25},{name:'dextroamphetamine sulfate',ratio:.25},{name:'amphetamine sulfate',ratio:.25}],note:'Total labeled mass of four salts; no active-base conversion. The d- and l-amphetamine concentration profiles would require separate models. '+assumedNote}),
  product('amphetamine-salts-ir','Mixed amphetamine salts IR (generic)','mixed amphetamine salts','Immediate-release tablet','Amphetamine',['5','7.5','10','12.5','15','20','30'],['C11'],{ingredients:[{name:'dextroamphetamine saccharate',ratio:.25},{name:'amphetamine aspartate monohydrate',ratio:.25},{name:'dextroamphetamine sulfate',ratio:.25},{name:'amphetamine sulfate',ratio:.25}]}),
  product('adderall-xr','Adderall XR','mixed amphetamine salts','Extended-release capsule','Amphetamine',['5','10','15','20','25','30'],['S4'],{unit:'capsule',ingredients:[{name:'dextroamphetamine saccharate',ratio:.25},{name:'amphetamine aspartate monohydrate',ratio:.25},{name:'dextroamphetamine sulfate',ratio:.25},{name:'amphetamine sulfate',ratio:.25}]}),
  product('amphetamine-salts-er','Mixed amphetamine salts ER (generic)','mixed amphetamine salts','Extended-release capsule','Amphetamine',['5','10','15','20','25','30'],['S4'],{unit:'capsule',ingredients:[{name:'dextroamphetamine saccharate',ratio:.25},{name:'amphetamine aspartate monohydrate',ratio:.25},{name:'dextroamphetamine sulfate',ratio:.25},{name:'amphetamine sulfate',ratio:.25}]}),
  product('mydayis','Mydayis','mixed amphetamine salts','Extended-release three-bead capsule','Amphetamine',['12.5','25','37.5','50'],['S4'],{unit:'capsule',ingredients:[{name:'dextroamphetamine saccharate',ratio:.25},{name:'amphetamine aspartate monohydrate',ratio:.25},{name:'dextroamphetamine sulfate',ratio:.25},{name:'amphetamine sulfate',ratio:.25}]}),
  product('evekeo','Evekeo','amphetamine sulfate','Immediate-release tablet','Amphetamine',['5','10'],['C12']),
  product('evekeo-odt','Evekeo ODT','amphetamine sulfate','Immediate-release orally disintegrating tablet','Amphetamine',['5','10','15','20'],['C13']),
  product('dyanavel-xr-liquid','Dyanavel XR suspension','amphetamine base','Extended-release oral suspension','Amphetamine',['2.5'],['C14'],{unit:'mL',strengthUnit:'mg/mL'}),
  product('dyanavel-xr-tablet','Dyanavel XR tablet','amphetamine base','Extended-release tablet','Amphetamine',['5','10','15','20'],['C14'],{note:'May be chewed or swallowed whole as labeled. Only the 5 mg tablet is functionally scored. '+assumedNote}),
  product('adzenys-xr-odt','Adzenys XR-ODT','amphetamine base','Extended-release orally disintegrating tablet','Amphetamine',['3.1','6.3','9.4','12.5','15.7','18.8'],['C15']),
  product('zenzedi','Zenzedi','dextroamphetamine sulfate','Immediate-release tablet','Dextroamphetamine',['2.5','5','7.5','10','15','20','30'],['C16']),
  product('procentra','ProCentra','dextroamphetamine sulfate','Immediate-release oral solution','Dextroamphetamine',['1'],['C17'],{unit:'mL',strengthUnit:'mg/mL',note:'5 mg/5 mL (1 mg/mL). '+assumedNote}),
  product('dexedrine-spansule','Dexedrine Spansule','dextroamphetamine sulfate','Sustained-release capsule','Dextroamphetamine',['5','10','15'],['C18'],{unit:'capsule'}),
  product('dextroamphetamine-ir','Dextroamphetamine IR (generic)','dextroamphetamine sulfate','Immediate-release tablet','Dextroamphetamine',['2.5','5','7.5','10','15','20','30'],['C26'],{note:'Generic family shortcut; strengths verified against a Winder label. Confirm the actual manufacturer, package strength and formulation; scoring is package-specific. '+assumedNote}),
  product('xelstrym','Xelstrym','dextroamphetamine','Transdermal system','Dextroamphetamine',['4.5','9','13.5','18'],['S9'],{unit:'patch',strengthUnit:'mg/9 h',route:'transdermal',note:'Labeled delivery over 9 hours; patch content is larger. Record application and removal. '+assumedNote}),
  product('vyvanse-capsule','Vyvanse capsule','lisdexamfetamine dimesylate','Prodrug capsule','Lisdexamfetamine',['10','20','30','40','50','60','70'],['S5'],{unit:'capsule'}),
  product('vyvanse-chewable','Vyvanse chewable','lisdexamfetamine dimesylate','Prodrug chewable tablet','Lisdexamfetamine',['10','20','30','40','50','60'],['S5']),
  product('lisdexamfetamine-capsule','Lisdexamfetamine capsule (generic)','lisdexamfetamine dimesylate','Prodrug capsule','Lisdexamfetamine',['10','20','30','40','50','60','70'],['S5'],{unit:'capsule'}),
  product('lisdexamfetamine-chewable','Lisdexamfetamine chewable (generic)','lisdexamfetamine dimesylate','Prodrug chewable tablet','Lisdexamfetamine',['10','20','30','40','50','60'],['S5']),
  product('arynta','Arynta','lisdexamfetamine dimesylate','Prodrug oral solution','Lisdexamfetamine',['10'],['S13'],{unit:'mL',strengthUnit:'mg/mL'}),
  product('desoxyn','Desoxyn','methamphetamine hydrochloride','Immediate-release tablet','Methamphetamine',['5'],['C19']),
  product('atomoxetine','Atomoxetine (Strattera reference)','atomoxetine','Capsule','Atomoxetine',['10','18','25','40','60','80','100'],['S10'],{unit:'capsule',note:'Retains Strattera as a searchable reference; confirm current generic package labeler. A daily concentration peak is not an immediate effect window. '+assumedNote}),
  product('intuniv','Intuniv / guanfacine ER','guanfacine','Extended-release tablet','Guanfacine',['1','2','3','4'],['C20'],{note:'ER formulation only. Immediate-release guanfacine is a separate formulation with different exposure. '+assumedNote}),
  product('clonidine-er','Clonidine ER (Kapvay reference)','clonidine hydrochloride','Extended-release tablet','Clonidine',['0.1'],['C21'],{note:'ADHD ER tablet family. Do not split, crush or chew. Other clonidine ER products are not automatically equivalent. '+assumedNote}),
  product('onyda-xr','Onyda XR','clonidine hydrochloride','Extended-release oral suspension','Clonidine',['0.1'],['S12'],{unit:'mL',strengthUnit:'mg/mL'}),
  product('qelbree','Qelbree','viloxazine','Extended-release capsule','Viloxazine',['100','150','200'],['S11'],{unit:'capsule'}),
  product('simtriyo','Simtriyo','centanafadine','Extended-release capsule','Centanafadine',['140','210','280'],['S14','S15'],{unit:'capsule',note:'FDA approval July 24, 2026. Classified as a CNS stimulant. Slightly greater-than-dose-proportional exposure prevents assuming linear PK scaling. '+assumedNote}),
  product('metformin-ir','Metformin IR (generic)','metformin hydrochloride','Immediate-release tablet','Metformin',['500','850','1000'],['C22'],{note:'Additional medication for record-keeping. Labeled for type 2 diabetes, not ADHD. Strengths preserve the hydrochloride basis. '+assumedNote}),
  product('metformin-er','Metformin ER (generic)','metformin hydrochloride','Extended-release tablet (500 / 750 mg family)','Metformin',['500','750'],['C23'],{note:'Additional medication for record-keeping. Labeled for type 2 diabetes, not ADHD. Confirm this ER formulation on the package; swallow whole, never crush, cut or chew. '+assumedNote}),
  product('metformin-er-osmotic','Metformin osmotic ER (generic)','metformin hydrochloride','Osmotic extended-release tablet','Metformin',['500','1000'],['C24'],{note:'Additional medication for record-keeping. Labeled for type 2 diabetes, not ADHD. Distinct from the conventional 500 / 750 mg ER family; swallow whole, never crush, cut or chew. '+assumedNote}),
  product('metformin-solution','Metformin oral solution (Riomet reference)','metformin hydrochloride','Immediate-release oral solution','Metformin',['100'],['C25'],{unit:'mL',strengthUnit:'mg/mL',note:'Additional medication for record-keeping. Labeled for type 2 diabetes, not ADHD. Historical Riomet reference: 500 mg/5 mL (100 mg/mL); record administered mL and confirm the bottle. This is not an ER suspension. '+assumedNote}),
];

export function getProduct(id:string):Product {
  const found = products.find(p=>p.id===id);
  if (!found) throw new Error(`Unknown medication product ID: ${id}. Its saved product snapshot must be reviewed before editing or modeling.`);
  return found;
}
