import type { PkReferenceProfile } from './pk-reference-types';

/** Formulation-specific reference illustrations; package mg never means analyte mg. */
export const AMPHETAMINE_PK_REFERENCES: readonly PkReferenceProfile[] = [
  {
    id: 'mixed-amphetamine-salts-ir-10mg',
    productIds: ['adderall-ir', 'amphetamine-salts-ir'],
    label: 'Mixed amphetamine salts IR · adult reference',
    referenceDoseMg: 10,
    unit: 'tablet',
    strengthUnit: 'mg',
    channels: [
      { group: 'd-Amphetamine', cmax: 15.7, peakHours: 2.72, halfLifeHours: 10.9 },
      { group: 'l-Amphetamine', cmax: 5.02, peakHours: 2.89, halfLifeHours: 13.5 },
    ],
    sourceIds: ['A1'],
    population: 'Healthy adults after one 10 mg tablet, overnight fast; 18 enrolled, 17 completed.',
    note: 'Constructed curves from FDA study 371.102 new-formulation means, not sampled concentration traces. Dose is the labeled total of four salts. Each enantiomer has its own concentration; do not add them as equivalent activity. Other strengths, split-tablet amounts, generic transfer and repeated-dose sums are proportional illustrations. Dose proportionality was studied at 10 and 30 mg; lower amounts are extrapolations. This does not establish that a particular tablet may be split.',
    fractionalTablets: true,
  },
  {
    id: 'mixed-amphetamine-salts-xr-30mg',
    productIds: ['adderall-xr', 'amphetamine-salts-er'],
    label: 'Mixed amphetamine salts XR · adult reference',
    referenceDoseMg: 30,
    unit: 'capsule',
    strengthUnit: 'mg',
    channels: [
      { group: 'd-Amphetamine', cmax: 44.3, peakHours: 5.2, halfLifeHours: 10.4 },
      { group: 'l-Amphetamine', cmax: 13.3, peakHours: 5.6, halfLifeHours: 12.7 },
    ],
    sourceIds: ['A6'],
    population: '19 healthy adult volunteers after one 30 mg Adderall XR capsule, fasted; study 381.103.',
    note: 'A smooth constructed approximation of the XR-specific study peak and half-life. It does not reconstruct the two-bead release mechanism or a measured concentration trace. Dose is labeled mixed-salt mg, not amphetamine-base mg. Other intact-capsule strengths, generic transfer and repeated-dose sums are proportional approximations. High-fat food delayed the study peaks to 7.7 h and 8.3 h; this fasted reference does not model that change. Do not substitute this profile for Mydayis, Dyanavel or Adzenys.',
  },
  {
    id: 'dextroamphetamine-sulfate-ir-15mg',
    productIds: ['zenzedi', 'dextroamphetamine-ir'],
    label: 'Dextroamphetamine IR · label reference',
    referenceDoseMg: 15,
    unit: 'tablet',
    strengthUnit: 'mg',
    channels: [{ group: 'd-Amphetamine', cmax: 36.6, peakHours: 3, halfLifeHours: 12 }],
    sourceIds: ['A2'],
    population: '12 healthy subjects; one dose of three 5 mg immediate-release tablets.',
    note: 'Constructed from the label comparison of IR tablets with a sustained-release capsule. The label does not give the age distribution or meal condition for this comparison. Dose is dextroamphetamine sulfate; the curve measures dextroamphetamine. Other strengths, split-tablet amounts, labeler transfer and repeated-dose sums use unvalidated proportional scaling. This does not establish that a particular tablet may be split.',
    fractionalTablets: true,
  },
  {
    id: 'dexedrine-spansule-15mg',
    productIds: ['dexedrine-spansule'],
    label: 'Dexedrine Spansule · label reference',
    referenceDoseMg: 15,
    unit: 'capsule',
    strengthUnit: 'mg',
    channels: [{ group: 'd-Amphetamine', cmax: 23.5, peakHours: 8, halfLifeHours: 12 }],
    sourceIds: ['A3'],
    population: '12 healthy subjects; one 15 mg sustained-release capsule.',
    note: 'A smooth constructed approximation using the capsule-specific peak and half-life, not a reconstruction of its release mechanism or measured trace. The label does not give the age distribution or meal condition for this comparison. Other intact-capsule strengths and repeated-dose sums use unvalidated proportional scaling of labeled dextroamphetamine sulfate mg.',
  },
  {
    id: 'lisdexamfetamine-capsule-70mg',
    productIds: ['vyvanse-capsule', 'lisdexamfetamine-capsule'],
    label: 'Lisdexamfetamine capsule · adult reference',
    referenceDoseMg: 70,
    unit: 'capsule',
    strengthUnit: 'mg',
    channels: [{ group: 'd-Amphetamine', cmax: 71.75, peakHours: 3.70, halfLifeHours: 11.3, lagHours: 0.839 }],
    sourceIds: ['A4', 'A5'],
    population: 'Healthy adults, fasted, one 70 mg Vyvanse capsule; study 2793, 28 completers.',
    note: 'Constructed active-dextroamphetamine curve using the study geometric-mean Cmax and median Tmax. An estimated 0.839 h lag is fitted to the study AUC0–1.5h of 15.63 ng·h/mL, not a measured absorption delay or proof of a drug-free interval. The 11.3 h half-life is a selected adult label reference within 10–11.3 h, not measured in this comparison. The resulting AUC0–4h is 177.95 versus 163.40 reported, and total AUC is 1394.09 versus 1492.39. Dose remains lisdexamfetamine dimesylate mg. This is not parent-lisdexamfetamine concentration or a mechanistic prodrug model. Other doses, generic transfer and repeated-dose sums are approximations; adult dose proportionality was reported at 50–250 mg, so amounts below 50 mg are extrapolations. Food can delay the peak.',
  },
  {
    id: 'lisdexamfetamine-chewable-60mg',
    productIds: ['vyvanse-chewable', 'lisdexamfetamine-chewable'],
    label: 'Lisdexamfetamine chewable · adult reference',
    referenceDoseMg: 60,
    unit: 'tablet',
    strengthUnit: 'mg',
    channels: [{ group: 'd-Amphetamine', cmax: 56.9, peakHours: 4.4, halfLifeHours: 12.7, lagHours: 0.740 }],
    sourceIds: ['A7', 'A5'],
    population: 'Healthy adults, fasted, one 60 mg chewable tablet per period; 18 subjects in a replicated crossover, 36 observations per formulation.',
    note: 'Constructed active-dextroamphetamine curve using the same study arithmetic-mean Cmax, Tmax and 12.7 h half-life. An estimated 0.740 h lag is fitted to AUC0–4h of 135 ng·h/mL, not a measured absorption delay or proof of a drug-free interval. The resulting AUC0–5h is 191.81 versus 188 reported, and total AUC is 1273.05 versus 1168. Dose remains lisdexamfetamine dimesylate mg. Other intact-tablet doses, generic transfer and repeated-dose sums use proportional approximations; adult proportionality below 50 mg is extrapolated. Do not use parent-lisdexamfetamine PK or the capsule peak for this profile.',
  },
  {
    id: 'lisdexamfetamine-solution-70mg',
    productIds: ['arynta'],
    label: 'Arynta oral solution · adult reference',
    referenceDoseMg: 70,
    unit: 'mL',
    strengthUnit: 'mg/mL',
    channels: [{ group: 'd-Amphetamine', cmax: 72.61, peakHours: 3.42, halfLifeHours: 11.3, lagHours: 0.677 }],
    sourceIds: ['A4', 'A5'],
    population: 'Healthy adults, fasted, one 7 mL dose of 10 mg/mL solution; study 2793, 28 completers.',
    note: 'Constructed active-dextroamphetamine curve using the solution-specific geometric-mean Cmax and median Tmax. An estimated 0.677 h lag is fitted to the study AUC0–1.5h of 24.09 ng·h/mL, not a measured absorption delay or proof of a drug-free interval. The 11.3 h half-life is a selected adult label reference, not measured in this comparison. The resulting AUC0–4h is 194.07 versus 182.46 reported, and total AUC is 1400.63 versus 1479.12. Volume is converted only to labeled lisdexamfetamine dimesylate mg, not active-base mg. Other volumes and repeated-dose sums are proportional approximations; lower doses extend beyond the 70 mg comparison. Food can delay the peak.',
  },
];
