export type Evidence = 'A'|'B'|'C'|'D';
export interface Product {id:string; name:string; generic:string; formulation:string; family:string; unit:string; strengths:string[]; strengthUnit:string; manufacturer:string; evidence:Evidence; model:'concerta'|'ritalin'|'assumption'; sourceIds:string[]; note:string; ingredients?:{name:string;ratio:number}[]; route?:string; status?:string; referenceDose?:number;}
export interface Source {id:string; title:string; url:string; section:string; reviewed:string; note:string;}
export interface Assumptions {peakHours:number;halfLifeHours:number;lagHours:number;referenceDose:number;amplitude:number; onsetHours:number;durationMinHours:number;durationMaxHours:number;durationOrigin:'from_onset'|'from_administration';accepted:boolean;}
export interface Dose {id:string;productId:string;productName:string;formulation:string;strength:string;packageStrength?:string;strengthUnit?:string;manufacturer?:string;amountBasis?:'labeled ingredient'|'first listed ingredient'|'labeled delivery over 9 hours';quantity:string;unit:string;amountMg:string;administeredAt:string;timeZone:string;status:'actual'|'planned'|'skipped'|'simulated';note:string;revision?:number;date?:string;time?:string;disambiguation?:'earlier'|'later';assumptions?:Assumptions;modelVersion?:string;unusual?:boolean;removalAt?:string;ingredients?:{name:string;amountMg:string;strengthMg?:string;unit?:string}[];}
export type TimeIncrementMinutes = 1|5|10;
export interface Profile {name:string;timeZone:string;timeFormat:'12h'|'24h';sleepEnabled:boolean;bedtime:string;wakeTime:string;weekendEnabled:boolean;weekendBedtime:string;weekendWakeTime:string;revision?:number;timeIncrementMinutes?:TimeIncrementMinutes;}
export interface Scenario {id:string;name:string;doses:Dose[];comparisonDoses?:Dose[];modelVersion:string;baseline:'empty'|'recorded';baselineNote?:string;revision?:number;view?:{date:string;days:number;timeZone:string;publishedOnly:boolean};}
export interface Favorite {id:string;productId:string;strength:string;packageStrength?:string;quantity:string;inventory?:string;revision?:number;}
export interface Checkin {id:string;date:string;focus?:string;sleepQuality?:string;note?:string;revision?:number;symptoms?:string[];recordedAt?:string;timeZone?:string;}
export interface InventoryReceipt {id:string;productId:string;productName:string;packageStrength:string;strengthUnit:string;unit:string;quantity:string;receivedAt:string;timeZone:string;note:string;revision?:number;}
export interface AppData {inventory?:InventoryReceipt[];profile:Profile|null;doses:Dose[];scenarios:Scenario[];favorites:Favorite[];checkins:Checkin[];}
export interface User {id:string;email:string;name:string;}
