import { useState } from 'react';
import { Search } from 'lucide-react';
import { products } from '../lib/catalog';
import type { Favorite } from '../lib/types';
import Modal from './Modal';
export default function FavoritePicker({favorites,onSave,onRemove,onClose}:{favorites:Favorite[];onSave:(f:Favorite)=>Promise<void>|void;onRemove:(f:Favorite)=>Promise<void>|void;onClose:()=>void}){
  const [selection,setSelection]=useState<Record<string,string>>(()=>Object.fromEntries(favorites.map(f=>[f.productId,f.packageStrength||f.strength]))),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const groups=[...new Set(products.map(p=>p.family))];
  return <Modal title="Choose medications" wide onClose={onClose}><label className="search-input"><Search size={16}/><input placeholder="Search brand or ingredient" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="catalog-groups">{groups.map(group=>{const list=products.filter(p=>p.family===group&&`${p.name} ${p.generic} ${p.formulation}`.toLowerCase().includes(query.toLowerCase()));if(!list.length)return null;return <section className="catalog-group" key={group}><h3>{group}</h3>{list.map(p=><div className="catalog-item" key={p.id}><label><input type="checkbox" checked={p.id in selection} onChange={e=>{const checked=e.currentTarget.checked;setSelection(v=>{const next={...v};if(checked)next[p.id]=p.strengths[0];else delete next[p.id];return next;});}}/><span><strong>{p.name}</strong><small>{p.formulation}</small></span></label>{p.id in selection&&<label className="field"><span>Preferred strength · {p.strengthUnit}</span><select aria-label={`${p.name} preferred strength`} value={selection[p.id]} onChange={e=>{const value=e.currentTarget.value;setSelection(v=>({...v,[p.id]:value}));}}>{p.strengths.map(s=><option key={s}>{s}</option>)}</select></label>}</div>)}</section>;})}</div>{error&&<p className="inline-error" role="alert">{error}</p>}<div className="modal-footer"><span className="muted">{Object.keys(selection).length} selected</span><button className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy} onClick={async()=>{setBusy(true);try{for(const f of favorites)if(!(f.productId in selection))await onRemove(f);for(const [productId,packageStrength] of Object.entries(selection)){const existing=favorites.find(f=>f.productId===productId);if(existing&&(existing.packageStrength||existing.strength)===packageStrength)continue;await onSave({id:existing?.id||crypto.randomUUID(),productId,packageStrength,strength:packageStrength.split('/')[0],quantity:existing?.quantity||'1',revision:existing?.revision});}onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Saving…':'Save selection'}</button></div></Modal>;
}
