import { useCallback, useEffect, useRef, useState } from 'react';
import { Pill, Plus, Check, ChevronLeft, ChevronRight, Download, CalendarDays, LogOut, X } from 'lucide-react';
import type { AppData, Dose, Favorite, Profile, Scenario, User, InventoryReceipt, Checkin } from './lib/types';
import { products, sources } from './lib/catalog';
import { api, cacheData, clearCache, queueCount, queueMutation, syncQueue, pendingChanges, discardPendingChange } from './lib/api';
import { addDays, dayWindow, formatInstant, instantToLocal, sleepIntervals, todayInZone } from './lib/time';
import { MODEL_VERSION } from './lib/model';
import { favoriteKey, upsertFavorite } from './lib/favorites';
import { scopeTimeline } from './lib/timeline-scope';
import { doseIngredientNames, ingredientAmount, exactSumValues as exactSum } from './lib/history-amounts';
import { downloadCsv, downloadPdf, filterDoses, parseBackup, summarize } from './lib/reports';
import TimelineChart from './components/TimelineChart';
import DoseEditor, { newDose, updateDose, doseInputError, currentDoseTime } from './components/DoseEditor';
import AuthDialog from './components/AuthDialog';
import Modal from './components/Modal';
import Inventory from './components/Inventory';
import FavoritePicker from './components/FavoritePicker';
import Symptoms from './components/Symptoms';
import SymptomHistory from './components/SymptomHistory';

type Page='Dose Simulation'|'History'|'Settings';
function validViewDate(value:string){try{return /^\d{4}-\d{2}-\d{2}$/.test(value)&&value>='0001-01-01'&&value<='9998-12-31'&&addDays(value,0)===value;}catch{return false;}}
const localZone=Intl.DateTimeFormat().resolvedOptions().timeZone;
const emptyData=():AppData=>({profile:null,doses:[],scenarios:[],favorites:[],checkins:[]});
const defaultProfile=():Profile=>({name:'',timeZone:localZone,timeFormat:'12h',sleepEnabled:false,bedtime:'',wakeTime:'',weekendEnabled:false,weekendBedtime:'',weekendWakeTime:''});
function blankDose(profile:Profile):Dose{return {...newDose(),productId:'',productName:'',formulation:'',strength:'',packageStrength:'',amountMg:'',ingredients:[],...currentDoseTime(profile.timeZone,profile.timeIncrementMinutes||5)};}
function amountLabel(d:Dose){return d.amountBasis==='labeled delivery over 9 hours'?`${d.amountMg} mg nominal / 9 h`:d.ingredients?.length===4&&d.amountBasis==='labeled ingredient'?`${d.amountMg} mg labeled salts`:d.ingredients&&d.ingredients.length>1?d.ingredients.map(i=>`${i.amountMg} mg ${i.name}`).join(' + '):`${d.amountMg} mg`;}

export default function App(){
  const [page,setPage]=useState<Page>('Dose Simulation'),[user,setUser]=useState<User|null>(null),[data,setData]=useState<AppData>(emptyData),[profile,setProfile]=useState<Profile>(defaultProfile),[auth,setAuth]=useState(false);
  const [date,setDate]=useState(todayInZone(localZone)),[days,setDays]=useState(1),[drafts,setDrafts]=useState<Dose[]>([]),[publishedOnly,setPublishedOnly]=useState(false),[savedPlan,setSavedPlan]=useState<Scenario|null>(null);
  const [pending,setPending]=useState(0),[error,setError]=useState(''),[toast,setToast]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Dose|null>(null),[loading,setLoading]=useState(true);
  const account=useRef<string|null>(null),generation=useRef(0),draftsRef=useRef(drafts);
  useEffect(()=>{draftsRef.current=drafts;},[drafts]);
  const notify=(text:string)=>setToast(text);
  const fetchAccount=useCallback(async(u:User,transition=false)=>{
    if(transition){account.current=u.id;generation.current++;}
    const token=generation.current;
    const incoming=await api<AppData>('/data','GET',undefined,u.id);
    if(token!==generation.current||account.current!==u.id)return;
    const visible=await cacheData(u.id,incoming);
    if(token!==generation.current||account.current!==u.id)return;
    setData(visible);setProfile(visible.profile||defaultProfile());setUser(u);setPending(await queueCount(u.id));
    if(transition){const plan=visible.scenarios.find(s=>s.name==='Workspace');if(plan){setDrafts(plan.doses.map(d=>({...d,modelVersion:d.modelVersion||plan.modelVersion})));setSavedPlan(plan);setPublishedOnly(plan.view?.publishedOnly??false);if(plan.view){setDate(plan.view.date);setDays(plan.view.days);}}}
  },[]);
  useEffect(()=>{api<{user:User|null}>('/session').then(async r=>{if(r.user)await fetchAccount(r.user,true);}).catch(()=>setError('Local server unavailable. Start Drug Tracker, then reload.')).finally(()=>setLoading(false));},[fetchAccount]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(t);},[toast]);
  async function refresh(){if(!user)return;const id=user.id,token=generation.current;try{await syncQueue(id);if(token!==generation.current||account.current!==id)return;await fetchAccount(user);notify('Saved to this Mac.');}catch(e){setError((e as Error).message);}}
  useEffect(()=>{const handler=()=>{if(user)void refresh();};window.addEventListener('online',handler);return()=>window.removeEventListener('online',handler);},[user]);
  async function mutate<T>(path:string,body:T,method='PUT'):Promise<T>{
    if(!user)throw new Error('Sign in to record doses.');const owner=user.id,token=generation.current;
    try{const result=await api<T>(path,method,body,owner);if(token!==generation.current||account.current!==owner)throw new Error('Account changed. Reload before continuing.');return result;}
    catch(e){if(e instanceof TypeError){if(token!==generation.current||account.current!==owner)throw new Error('Account changed.');await queueMutation(owner,path,body,method);setPending(await queueCount(owner));return body;}throw e;}
  }
  function resetAccount(){generation.current++;account.current=null;setUser(null);setData(emptyData());setProfile(defaultProfile());setDrafts([]);setSavedPlan(null);setEditing(null);setPending(0);setError('');}
  async function signOut(){if(!user)return;try{if(await queueCount(user.id))throw new Error('Resolve pending changes in Settings before signing out.');await api('/auth/logout','POST',{});generation.current++;account.current=null;await clearCache(user.id);resetAccount();notify('Signed out.');}catch(e){setError((e as Error).message);}}
  async function savePlan(rows=drafts){if(!user){setAuth(true);return;}try{const plan:Scenario={id:savedPlan?.id||crypto.randomUUID(),name:'Workspace',doses:rows,modelVersion:MODEL_VERSION,baseline:'recorded',baselineNote:'Includes actual history currently loaded; earlier history may be incomplete.',revision:savedPlan?.revision,view:{date,days,timeZone:profile.timeZone,publishedOnly}};const result=await mutate(`/scenarios/${plan.id}`,plan);setSavedPlan(result);setData(d=>({...d,scenarios:[...d.scenarios.filter(s=>s.id!==result.id),result]}));notify(await queueCount(user.id)?'Plan saved on device; pending sync.':'Plan saved.');}catch(e){setError((e as Error).message);}}
  function addDose(f?:Favorite){if(!data.favorites.length){setPage('Settings');notify('Choose your medications first.');return;}const row=f?updateDose(newDose(f.productId,f.packageStrength||f.strength),{quantity:f.quantity},profile.timeZone):blankDose(profile);Object.assign(row,currentDoseTime(profile.timeZone,profile.timeIncrementMinutes||5),{timeZone:profile.timeZone});setDrafts(v=>[...v,row]);requestAnimationFrame(()=>document.querySelector<HTMLSelectElement>(`select[aria-label="Dose ${drafts.length+1} medication"]`)?.focus());}
  async function markTaken(d:Dose){if(!user){setAuth(true);return;}setBusy(true);setError('');try{const issue=doseInputError(d);if(issue)throw new Error(issue);if(!d.administeredAt)throw new Error('Choose a date and time first.');if(Date.parse(d.administeredAt)>Date.now()+60000)throw new Error('This time is in the future. Mark Taken after the dose was actually taken.');const row={...d,status:'actual' as const};delete row.revision;const saved=await mutate(`/doses/${row.id}`,row);setData(v=>({...v,doses:[...v.doses.filter(x=>x.id!==saved.id),saved]}));const remaining=draftsRef.current.filter(v=>v.id!==d.id);setDrafts(v=>v.filter(row=>row.id!==d.id));if(savedPlan){const updated={...savedPlan,doses:remaining};try{const s=await mutate(`/scenarios/${updated.id}`,updated);setSavedPlan(s);}catch{setError('The dose is recorded. Save the plan again to update its draft list.');}}notify(await queueCount(user.id)?'Taken recorded on device; pending sync.':'Recorded as taken.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function undoTaken(d:Dose){if(!window.confirm('Remove this taken record and return it to the plan?'))return;try{await mutate(`/doses/${d.id}`,{revision:d.revision},'DELETE');setData(v=>({...v,doses:v.doses.filter(x=>x.id!==d.id)}));const copy={...d,id:crypto.randomUUID(),status:'simulated' as const};delete copy.revision;setDrafts(v=>[...v,copy]);notify('Returned to the plan.');}catch(e){setError((e as Error).message);}}
  async function saveEdit(){if(!editing)return;setBusy(true);try{const issue=doseInputError(editing);if(issue)throw new Error(issue);if(!editing.administeredAt)throw new Error('Enter a complete date and time.');if(Date.parse(editing.administeredAt)>Date.now()+60000)throw new Error('An actual dose cannot be in the future.');const saved=await mutate(`/doses/${editing.id}`,editing);setData(v=>({...v,doses:v.doses.map(x=>x.id===saved.id?saved:x)}));setEditing(null);notify('Record corrected.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function saveCheckin(entry:Checkin){if(!user){setAuth(true);throw new Error('Unlock to save a check-in.');}const saved=await mutate(`/checkins/${entry.id}`,entry);setData(v=>({...v,checkins:[...v.checkins.filter(c=>c.id!==saved.id),saved]}));notify('Check-in saved.');}
  async function removeCheckin(entry:Checkin){await mutate(`/checkins/${entry.id}`,{revision:entry.revision},'DELETE');setData(v=>({...v,checkins:v.checkins.filter(c=>c.id!==entry.id)}));notify('Check-in deleted.');}
  const actual=data.doses.filter(d=>d.status==='actual');
  const actualIds=new Set(actual.map(d=>d.id));
  const activeDrafts=drafts.filter(d=>!actualIds.has(d.id));
  const windowRange=dayWindow(date,days,profile.timeZone);
  const scoped=scopeTimeline({actual,drafts:activeDrafts,start:windowRange.start,end:windowRange.end,publishedOnly});
  const shownActual=actual.filter(d=>Date.parse(d.administeredAt)>=windowRange.start&&Date.parse(d.administeredAt)<windowRange.end).sort((a,b)=>Date.parse(a.administeredAt)-Date.parse(b.administeredAt));
  return <div className="simple-shell"><header className="app-header"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('Dose Simulation');}}><Pill size={22}/><span>Drug Tracker</span></a><nav className="app-nav" aria-label="Main navigation">{(['Dose Simulation','History','Settings'] as Page[]).map(p=><button className={page===p?'active':''} aria-current={page===p?'page':undefined} key={p} onClick={()=>{setPage(p);setError('');}}>{p}</button>)}</nav><div className="account-control">{user?<span className="local-status">{pending?`${pending} pending`:'Local account'}</span>:<button className="button secondary small" onClick={()=>setAuth(true)}>Unlock</button>}</div></header><main>
    <div className="page-title"><h1>{page}</h1></div>
    {loading&&<p className="notice">Connecting to the local database…</p>}{error&&<div className="error-banner" role="alert"><span>{error}</span><button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
    {page==='Dose Simulation'&&<><div className="toolbar simulation-toolbar"><div className="date-nav"><button className="icon-button" aria-label="Previous day" onClick={()=>setDate(addDays(date,-1))}><ChevronLeft size={18}/></button><label className="selected-date"><CalendarDays size={16}/><input aria-label="Chart date" type="date" value={date} onInput={e=>{if(validViewDate(e.currentTarget.value)){setDate(e.currentTarget.value);setError('');}else setError('Enter a valid date.');}}/></label><button className="icon-button" aria-label="Next day" onClick={()=>setDate(addDays(date,1))}><ChevronRight size={18}/></button><button className="text-button" onClick={()=>setDate(todayInZone(profile.timeZone))}>Today</button></div><button className="button primary mobile-add-dose" onClick={()=>addDose()}><Plus size={16}/>Add dose</button><div className="segmented">{[1,2,3].map(n=><button key={n} className={days===n?'selected':''} aria-pressed={days===n} onClick={()=>setDays(n)}>{n===1?'Day':`${n*24} hours`}</button>)}</div></div>

<section className="card timeline-card"><TimelineChart doses={scoped.doses} date={date} days={days} profile={profile} publishedOnly={publishedOnly} actual={false} baseline={user?'recorded':'empty'} onProfile={()=>setPage('Settings')} onMove={(id,iso)=>{if(actualIds.has(id))return;const parts=instantToLocal(iso,profile.timeZone);setDrafts(ds=>ds.map(d=>d.id===id?{...d,...parts,administeredAt:iso}:d));}}/><p className="simulation-notice">Reference estimates, not measured drug levels or dose advice. <button className="text-button" onClick={()=>{setPage('Settings');requestAnimationFrame(()=>document.getElementById('methods')?.scrollIntoView());}}>Sources & methods</button></p></section>
    <section className="card dose-card"><div className="section-heading"><h2>Doses</h2></div>
      {shownActual.map(d=><div className="taken-row" key={d.id}><span className="taken-check"><Check size={16}/></span><div className="taken-time">{formatInstant(Date.parse(d.administeredAt),profile,false)}<small>{instantToLocal(d.administeredAt,profile.timeZone).date}</small></div><div className="taken-product"><strong>{d.productName}</strong><small>{d.packageStrength||d.strength} {d.strengthUnit||'mg'} · {d.quantity} {d.unit}</small></div><span className="tag blue">Taken</span><button className="text-button" onClick={()=>{setEditing(d);setError('');}}>Edit</button><button className="icon-button" aria-label={`Undo taken ${d.productName}`} onClick={()=>void undoTaken(d)}><X size={15}/></button></div>)}
      {activeDrafts.map((d,i)=><div className="planned-row" key={d.id}><fieldset className="dose-fields" disabled={busy}><DoseEditor productIds={data.favorites.map(f=>f.productId)} dose={d} index={i} profile={profile} onChange={next=>{const f=data.favorites.find(f=>f.productId===next.productId);const row=d.productId!==next.productId&&f?updateDose(next,{packageStrength:f.packageStrength||f.strength,quantity:f.quantity},profile.timeZone):next;setDrafts(v=>v.map(x=>x.id===d.id?row:x));}} onRemove={()=>setDrafts(v=>v.filter(x=>x.id!==d.id))} onDuplicate={()=>setDrafts(v=>[...v,{...d,id:crypto.randomUUID()}])}/></fieldset><div className="row-state"><span className="muted">{d.administeredAt?'Planned':'New dose'}</span><button className="button secondary small" disabled={busy||!d.productId||!d.administeredAt} onClick={()=>void markTaken(d)}><Check size={15}/>Taken</button></div></div>)}
      {!shownActual.length&&!activeDrafts.length&&<div className="empty-state">No doses.</div>}
      <div className="dose-actions"><button className="button secondary desktop-add-dose" onClick={()=>addDose()}><Plus size={16}/>Add dose</button>{activeDrafts.length>0&&<button className="text-button" onClick={()=>void savePlan()}>Save plan</button>}{data.favorites.map(f=><button className="favorite-chip" key={f.id} onClick={()=>{try{addDose(f);}catch{setError('This saved product is not in the current catalog. Your old records are retained.');}}}><Plus size={13}/>{products.find(p=>p.id===f.productId)?.name||f.productId} {f.packageStrength||f.strength} {products.find(p=>p.id===f.productId)?.strengthUnit||''}</button>)}</div>
    </section><Symptoms checkins={data.checkins} profile={profile} onSave={saveCheckin} onRemove={removeCheckin}/><details className="advanced-options"><summary>Simulation options</summary><div className="advanced-content"><label className="check-line"><input type="checkbox" checked={publishedOnly} onChange={e=>setPublishedOnly(e.target.checked)}/>Published trace only (no estimated Concerta tail)</label></div></details>{scoped.sourceIds.length>0&&<details className="page-references"><summary>References</summary>{sources.filter(s=>scoped.sourceIds.includes(s.id)).map(s=><a key={s.id} href={s.url} target="_blank" rel="noreferrer">{s.title}<small>{s.section}</small></a>)}</details>}</>}
    {page==='History'&&(user?<History data={data} profile={profile} pending={pending} onSaveCheckin={saveCheckin} onRemoveCheckin={removeCheckin} onEdit={d=>{setEditing(d);setError('');}} onError={setError}/>:<div className="card sign-in-prompt"><p>Unlock to view history.</p><button className="button primary" onClick={()=>setAuth(true)}>Unlock</button></div>)}
    {page==='Settings'&&<SettingsPage profile={profile} data={data} user={user} pending={pending} onSignIn={()=>setAuth(true)} onSignOut={signOut} onRefresh={refresh} onProfile={async p=>{try{sleepIntervals(Date.now(),Date.now()+86400000,p);dayWindow(date,1,p.timeZone);if(user){const result=await mutate('/profile',p);setProfile(result);setData(v=>({...v,profile:result}));}else setProfile(p);notify(user&&await queueCount(user.id)?'Preferences saved on device; pending sync.':user?'Preferences saved.':'Preview preferences updated.');}catch(e){setError((e as Error).message);}}} onFavorite={async incoming=>{const existing=data.favorites.find(x=>favoriteKey(x)===favoriteKey(incoming));const f=existing?{...incoming,id:existing.id,revision:existing.revision}:incoming;if(!user){setData(v=>({...v,favorites:upsertFavorite(v.favorites,f)}));return;}try{const saved=await mutate(`/favorites/${f.id}`,f);setData(v=>({...v,favorites:upsertFavorite(v.favorites,saved)}));notify('Medication saved.');}catch(e){setError((e as Error).message);throw e;}}} onRemoveFavorite={async f=>{if(!user){setData(v=>({...v,favorites:v.favorites.filter(x=>x.id!==f.id)}));return;}try{await mutate(`/favorites/${f.id}`,{revision:f.revision},'DELETE');setData(v=>({...v,favorites:v.favorites.filter(x=>x.id!==f.id)}));}catch(e){setError((e as Error).message);throw e;}}} onReceipt={async r=>{if(!user){setAuth(true);throw new Error('Sign in to save supply records.');}const saved=await mutate(`/inventory/${r.id}`,r);setData(v=>({...v,inventory:[...(v.inventory||[]).filter(x=>x.id!==saved.id),saved]}));notify('Supply recorded.');}} onRemoveReceipt={async r=>{await mutate(`/inventory/${r.id}`,{revision:r.revision},'DELETE');setData(v=>({...v,inventory:(v.inventory||[]).filter(x=>x.id!==r.id)}));}} onImport={async(backup,mode)=>{if(!user)return;await api('/import','POST',{backup,mode},user.id);await fetchAccount(user,true);notify('Backup restored.');}} onDelete={async password=>{if(!user)return;await api('/account','DELETE',{password},user.id);await clearCache(user.id,true);resetAccount();notify('Local account deleted.');}}/>}
    <footer className="app-footer"><span>Local on this Mac</span></footer>
  </main>{auth&&<AuthDialog onClose={()=>setAuth(false)} onUser={u=>fetchAccount(u,true)}/>}{editing&&<Modal title="Edit taken dose" wide onClose={()=>{setEditing(null);setError('');}}><DoseEditor productIds={data.favorites.map(f=>f.productId)} actual dose={editing} index={0} profile={profile} onChange={setEditing}/>{error&&<p role="alert" className="inline-error">{error}</p>}<div className="modal-footer"><button className="button secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="button primary" disabled={busy} onClick={()=>void saveEdit()}>Save correction</button></div></Modal>}{toast&&<div className="toast" role="status"><Check size={16}/>{toast}<button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={14}/></button></div>}</div>;
}


function History({data,profile,pending,onEdit,onError,onSaveCheckin,onRemoveCheckin}:{onSaveCheckin:(entry:Checkin)=>Promise<void>;onRemoveCheckin:(entry:Checkin)=>Promise<void>;data:AppData;profile:Profile;pending:number;onEdit:(d:Dose)=>void;onError:(s:string)=>void}){
  const today=todayInZone(profile.timeZone),[month,setMonth]=useState(today.slice(0,7)),[range,setRange]=useState('month'),[productId,setProductId]=useState(''),[ingredient,setIngredient]=useState(''),[fromCustom,setFromCustom]=useState(today.slice(0,7)+'-01'),[toCustom,setToCustom]=useState(today),[exporting,setExporting]=useState(false);
  const first=month+'-01',last=addDays(addDays(first,32).slice(0,7)+'-01',-1);
  const from=range==='month'?first:range==='7'?addDays(today,-6):range==='30'?addDays(today,-29):range==='all'?[...data.doses.map(d=>d.administeredAt?instantToLocal(d.administeredAt,profile.timeZone).date:today),...data.checkins.map(c=>c.recordedAt?instantToLocal(c.recordedAt,profile.timeZone).date:c.date)].reduce((a,b)=>b&&b<a?b:a,today):fromCustom;
  const to=range==='month'?last:range==='custom'?toCustom:today;
  const selected=from&&to&&from<=to?filterDoses(data.doses,from,to,profile.timeZone):[];
  const choices=Array.from(new Map(selected.map(d=>[d.productId,d.productName])).entries());
  const selectedProduct=choices.some(([id])=>id===productId)?productId:choices[0]?.[0]||'';
  const rows=selected.filter(d=>d.productId===selectedProduct);
  const ingredients=Array.from(new Set(rows.flatMap(doseIngredientNames)));
  const selectedIngredient=ingredients.includes(ingredient)?ingredient:ingredients[0]||'';
  const quantityFor=(d:Dose)=>ingredientAmount(d,selectedIngredient);
  const hasPatch=rows.some(d=>d.amountBasis==='labeled delivery over 9 hours');
  const allGroups=Array.from(new Set(selected.map(d=>d.productId))).map(id=>{const r=selected.filter(d=>d.productId===id),names=Array.from(new Set(r.flatMap(doseIngredientNames)));return {id,name:r[0].productName,count:r.length,quantity:exactSum(r.map(d=>d.quantity)),unit:r[0].unit,labeledSalts:products.find(p=>p.id===id)?.ingredients?.length===4?exactSum(r.map(d=>d.amountMg)):null,patch:r.some(d=>d.amountBasis==='labeled delivery over 9 hours'),ingredients:names.map(name=>({name,total:exactSum(r.map(d=>ingredientAmount(d,name)))}))};});
  const dayCount=from&&to?Math.max(1,Math.round((Date.parse(to)-Date.parse(from))/86400000)+1):1;
  const monthly=dayCount>62;
  const periods:string[]=[];if(from&&to&&from<=to){if(monthly){let m=from.slice(0,7);while(m<=to.slice(0,7)&&periods.length<1200){periods.push(m);m=addDays(m+'-01',32).slice(0,7);}}else for(let i=0;i<dayCount;i++)periods.push(addDays(from,i));}
  const bars=periods.map(day=>{const rs=rows.filter(d=>{const dt=instantToLocal(d.administeredAt,profile.timeZone).date;return monthly?dt.startsWith(day):dt===day;});return {day,count:rs.length,value:Number(exactSum(rs.map(quantityFor)))};});
  const maximum=Math.max(1,...bars.map(b=>b.value));
  const summaries=summarize(rows,profile.timeZone);
  return <><div className="toolbar history-toolbar"><div className="date-nav"><button className="icon-button" aria-label="Previous month" onClick={()=>{setMonth(addDays(first,-1).slice(0,7));setRange('month');}}><ChevronLeft size={18}/></button><input aria-label="History month" type="month" value={month} onInput={e=>{if(/^\d{4}-\d{2}$/.test(e.currentTarget.value)&&validViewDate(e.currentTarget.value+'-01')){setMonth(e.currentTarget.value);setRange('month');onError('');}else onError('Enter a valid month.');}}/><button className="icon-button" aria-label="Next month" onClick={()=>{setMonth(addDays(first,32).slice(0,7));setRange('month');}}><ChevronRight size={18}/></button></div><select aria-label="History period" value={range} onChange={e=>setRange(e.target.value)}><option value="month">Calendar month</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="all">All time</option><option value="custom">Custom dates</option></select></div>{range==='custom'&&<div className="field-pair custom-history"><label className="field"><span>From</span><input type="date" value={fromCustom} onInput={e=>{if(!e.currentTarget.value||validViewDate(e.currentTarget.value)){setFromCustom(e.currentTarget.value);onError('');}else onError('Enter a valid date.');}}/></label><label className="field"><span>Through</span><input type="date" value={toCustom} onInput={e=>{if(!e.currentTarget.value||validViewDate(e.currentTarget.value)){setToCustom(e.currentTarget.value);onError('');}else onError('Enter a valid date.');}}/></label></div>}
  <div className="history-summary">{allGroups.filter(g=>g.id===selectedProduct).map(g=><button key={g.id} className={`card summary-card ${selectedProduct===g.id?'selected':''}`} onClick={()=>{setProductId(g.id);setIngredient('');}}><span>{g.name}</span>{g.labeledSalts?<strong>{g.labeledSalts} <small>mg labeled salts</small></strong>:g.ingredients.length===1?<strong>{g.ingredients[0].total} <small>mg{g.patch?' nominal':''}</small></strong>:<div className="ingredient-totals">{g.ingredients.map(i=><p key={i.name}><b>{i.total} mg</b> {i.name}</p>)}</div>}<small>{g.quantity} {g.unit} · {g.count} recorded dose{g.count===1?'':'s'}{g.patch?' · labeled 9 h delivery':''}</small></button>)}</div>
  <section className="card month-chart"><div className="section-heading"><h2>{monthly?'Monthly amount':'Daily amount'}</h2>{choices.length>0&&<select aria-label="Chart medication" value={selectedProduct} onChange={e=>{setProductId(e.target.value);setIngredient('');}}>{choices.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select>}</div>{ingredients.length>1&&<label className="ingredient-selector field"><span>Ingredient (separate labeled amounts)</span><select value={selectedIngredient} onChange={e=>setIngredient(e.target.value)}>{ingredients.map(i=><option key={i}>{i}</option>)}</select></label>}{rows.length?<><div className="bar-chart" role="img" aria-label={`${monthly?'Monthly':'Daily'} recorded amounts of ${selectedIngredient}, ${hasPatch?'nominal delivery':'mg'}, ${from} to ${to}`}><div className="bar-scale"><span>{maximum} mg</span><span>0</span></div><div className="bar-series">{bars.map((b,i)=><div className="bar-column" key={b.day}><div className="bar-space"><span className="bar" style={{height:`${b.value/maximum*100}%`,minHeight:b.count?3:0}} aria-label={`${b.day}: ${b.count?`${b.value} mg, ${b.count} recorded doses`:'no record'}`} title={`${b.day}: ${b.count?`${b.value} mg`:'No record'}`}/></div><span>{i===0||i===bars.length-1||i%Math.max(1,Math.ceil(bars.length/7))===0?monthly?b.day:b.day.slice(5):''}</span></div>)}</div></div>{hasPatch&&<p className="chart-caption">Nominal labeled delivery over 9 hours, not measured absorbed mass.</p>}</>:<div className="empty-state">No taken doses in this period.</div>}<p className="chart-caption">No record does not mean no dose. Planned doses are excluded.</p></section>
  <section className="card"><div className="section-heading"><div><h2>Records</h2><small className="muted">{from} – {to}</small></div><div className="export-actions"><button className="text-button" disabled={!from||!to||from>to} onClick={()=>downloadCsv(data.doses,profile,from,to,data.checkins)}><Download size={14}/>CSV</button><button className="text-button" disabled={exporting||!from||!to||from>to} onClick={async()=>{setExporting(true);try{await downloadPdf(selected,profile,from,to,pending);}catch(e){onError((e as Error).message);}finally{setExporting(false);}}}><Download size={14}/>{exporting?'Preparing…':'Medication PDF'}</button></div></div>{selected.length?<div className="table-wrap"><table><thead><tr><th>Time</th><th>Medication</th><th>Amount</th><th/></tr></thead><tbody>{[...selected].sort((a,b)=>Date.parse(b.administeredAt)-Date.parse(a.administeredAt)).map(d=><tr key={d.id}><td>{formatInstant(Date.parse(d.administeredAt),profile,true)}</td><td><strong>{d.productName}</strong><small>{d.formulation} · {d.packageStrength||d.strength} {d.strengthUnit||'mg'}</small></td><td>{amountLabel(d)}<small>{d.quantity} {d.unit}</small></td><td><button className="text-button" onClick={()=>onEdit(d)}>Edit</button></td></tr>)}</tbody></table></div>:<div className="empty-state">No records.</div>}{summaries.length>1&&<details className="record-details"><summary>Totals by package strength</summary>{summaries.map(s=><p key={s.key}>{s.product} · {s.strength} {s.strengthUnit}: {s.quantity} {s.unit}</p>)}</details>}</section><SymptomHistory checkins={data.checkins} doses={data.doses} profile={profile} from={from} to={to} onSave={onSaveCheckin} onRemove={onRemoveCheckin}/></>;
}

function SettingsPage({profile,data,user,pending,onSignIn,onSignOut,onRefresh,onProfile,onFavorite,onRemoveFavorite,onReceipt,onRemoveReceipt,onImport,onDelete}:{profile:Profile;data:AppData;user:User|null;pending:number;onSignIn:()=>void;onSignOut:()=>void;onRefresh:()=>Promise<void>;onProfile:(p:Profile)=>void;onFavorite:(f:Favorite)=>Promise<void>;onRemoveFavorite:(f:Favorite)=>Promise<void>;onReceipt:(r:InventoryReceipt)=>Promise<void>;onRemoveReceipt:(r:InventoryReceipt)=>Promise<void>;onImport:(backup:unknown,mode:'merge'|'replace')=>Promise<void>;onDelete:(password:string)=>Promise<void>}){
  const [draft,setDraft]=useState(profile),[choosing,setChoosing]=useState(false),[incoming,setIncoming]=useState<{data:AppData;archive:unknown}|null>(null),[importMode,setImportMode]=useState<'merge'|'replace'>('merge'),[deleting,setDeleting]=useState(false),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[outbox,setOutbox]=useState<Awaited<ReturnType<typeof pendingChanges>>>([]);
  useEffect(()=>setDraft(profile),[profile]);useEffect(()=>{if(user)pendingChanges(user.id).then(setOutbox);},[pending,user]);
  return <><div className="settings-grid"><form className="card settings-section" onSubmit={e=>{e.preventDefault();onProfile(draft);}}><h2>Personal settings</h2><label className="field"><span>Name (optional)</span><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="field"><span>Time zone</span><select value={draft.timeZone} onChange={e=>setDraft({...draft,timeZone:e.target.value})}>{Array.from(new Set([draft.timeZone,'UTC',...Intl.supportedValuesOf('timeZone')])).map(z=><option key={z}>{z}</option>)}</select></label><label className="field"><span>Clock format</span><select value={draft.timeFormat} onChange={e=>setDraft({...draft,timeFormat:e.target.value as Profile['timeFormat']})}><option value="12h">12 hour</option><option value="24h">24 hour</option></select></label><label className="field"><span>Time increment</span><select value={draft.timeIncrementMinutes||5} onChange={e=>setDraft({...draft,timeIncrementMinutes:Number(e.target.value) as 5|10})}><option value="5">5 minutes</option><option value="10">10 minutes</option></select></label><label className="check-line"><input type="checkbox" checked={draft.sleepEnabled} onChange={e=>setDraft({...draft,sleepEnabled:e.target.checked})}/>Show sleep schedule</label>{draft.sleepEnabled&&<><div className="field-pair"><label className="field"><span>Bedtime</span><input type="time" required value={draft.bedtime} onInput={e=>setDraft({...draft,bedtime:e.currentTarget.value})}/></label><label className="field"><span>Wake time</span><input type="time" required value={draft.wakeTime} onInput={e=>setDraft({...draft,wakeTime:e.currentTarget.value})}/></label></div><details><summary>Weekend schedule</summary><label className="check-line"><input type="checkbox" checked={draft.weekendEnabled} onChange={e=>setDraft({...draft,weekendEnabled:e.target.checked})}/>Different weekend times</label>{draft.weekendEnabled&&<div className="field-pair"><label className="field"><span>Weekend bedtime</span><input type="time" required value={draft.weekendBedtime} onInput={e=>setDraft({...draft,weekendBedtime:e.currentTarget.value})}/></label><label className="field"><span>Weekend wake time</span><input type="time" required value={draft.weekendWakeTime} onInput={e=>setDraft({...draft,weekendWakeTime:e.currentTarget.value})}/></label></div>}</details></>}<button className="button primary" type="submit">Save settings</button>{!user&&<small className="muted">Preview</small>}</form>
  <section className="card settings-section"><h2>My medications</h2>{data.favorites.map(f=><div className="favorite-item" key={f.id}><span>{products.find(p=>p.id===f.productId)?.name||f.productId}<small>{f.packageStrength||f.strength} {products.find(p=>p.id===f.productId)?.strengthUnit||''}</small></span><button className="icon-button" aria-label="Remove favorite" onClick={()=>{void onRemoveFavorite(f).catch(()=>{});}}><X size={15}/></button></div>)}<button className="button secondary" onClick={()=>setChoosing(true)}><Plus size={15}/>Choose medications</button></section></div>
  <Inventory receipts={data.inventory||[]} doses={data.doses} favorites={data.favorites} profile={profile} onSave={onReceipt} onRemove={onRemoveReceipt}/>
  {choosing&&<FavoritePicker favorites={data.favorites} onSave={onFavorite} onRemove={onRemoveFavorite} onClose={()=>setChoosing(false)}/>}

  <section className="card settings-section"><div className="section-heading"><h2>Account & data</h2>{user?<button className="text-button" onClick={onSignOut}><LogOut size={15}/>Sign out</button>:<button className="button primary small" onClick={onSignIn}>Unlock</button>}</div><p className="muted">{user?'Local account.':'Locked.'} Data stays on this Mac. This version does not sync to a cloud server.</p><details className="privacy-details"><summary>Privacy</summary><p className="muted">Your password controls access to this local account. The database, browser cache, pending changes and downloaded backups are not end-to-end encrypted. Dose and check-in corrections may retain earlier versions. Full backups can include deleted-record history.</p><p className="muted">The app has no analytics or advertising services. Opening an external reference, GitHub or the project website contacts that site. Publishing the source code does not upload your health records.</p></details>{user&&<><div className="data-actions"><button className="button secondary" disabled={pending>0} onClick={async()=>{try{const backup=await api('/export','GET',undefined,user.id);const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='dose-timeline-backup.json';a.click();URL.revokeObjectURL(url);}catch(e){setError((e as Error).message);}}}><Download size={15}/>Full backup</button><label className="button secondary file-input">Import backup<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{const text=await file.text();setIncoming({data:parseBackup(text),archive:JSON.parse(text)});setImportMode('merge');setError('');}catch(e){setError((e as Error).message);}e.target.value='';}}/></label></div>{pending>0&&<details className="pending-panel" open><summary>{pending} pending changes</summary><button className="button secondary small" onClick={onRefresh}>Retry sync</button>{outbox.map(q=><div key={q.id} className="pending-item"><span>{q.path}<small>{q.method}</small></span><button className="text-button" onClick={async()=>{if(!window.confirm('Discard this unsynced change and keep the saved server record?'))return;await discardPendingChange(user.id,q.id);setOutbox(await pendingChanges(user.id));await onRefresh();}}>Keep server version</button></div>)}</details>}<details className="danger-zone"><summary>Delete account</summary><p className="muted">Deletes this account and its records from the local database.</p><button className="button danger" onClick={()=>setDeleting(true)}>Delete account and records</button></details></>}{error&&<p className="inline-error" role="alert">{error}</p>}</section>
  <details className="card methods-panel" id="methods"><summary>Sources & methods</summary><div className="methods-body"><p>This simulator does not measure your drug level or decide when to take medication. Follow your prescription and discuss changes with your clinician.</p><p>Concerta 18 mg uses a digitized adult group trace from the supplied build brief. After 29.976 h, an optional terminal tail assumes a 3.5 h half-life. Ritalin IR 10 mg uses a constructed first-order model anchored at 4.3 ng/mL and 2 h, with a cross-study 3.5 h half-life. The digitization checksum has not been independently reproduced.</p><p>Compatible reference curves are added across calendar days. Other strengths and products use explicit dimensionless assumptions, not product-specific concentration predictions. Unknown contributions remain unknown. Sleep shading is a target schedule, not a safety threshold.</p><p>A = published group reconstruction; B = parameter estimate; C = justified proxy (none enabled); D = assumption-only. Product approval, current marketing and pharmacy availability are different; current availability is not verified.</p></div></details>
  <div className="project-note"><span>Open-source project · Built with OpenAI Codex (GPT-6)</span><a href="https://github.com/Treeezheng/drug-tracker" target="_blank" rel="noreferrer">GitHub</a><a href="https://treeezh.com/drug" target="_blank" rel="noreferrer">Website · planned</a><a href={`${import.meta.env?.BASE_URL || '/'}LICENSE`} target="_blank" rel="noreferrer">0BSD license</a><a href={`${import.meta.env?.BASE_URL || '/'}privacy.html`} target="_blank" rel="noreferrer">Privacy</a></div>
  {incoming&&<Modal title="Import backup" onClose={()=>setIncoming(null)}><p>{incoming.data.doses.length} dose records · {incoming.data.scenarios.length} plans · {incoming.data.favorites.length} saved medications</p><label className="field"><span>Import method</span><select value={importMode} onChange={e=>setImportMode(e.target.value as 'merge'|'replace')}><option value="merge">Merge new records; keep existing IDs</option><option value="replace">Replace this account’s current records</option></select></label>{error&&<p className="inline-error" role="alert">{error}</p>}<div className="modal-footer"><button className="button secondary" onClick={()=>setIncoming(null)}>Cancel</button><button className="button primary" disabled={busy} onClick={async()=>{if(importMode==='replace'&&!window.confirm('Replace all records in this local account with this backup?'))return;setBusy(true);try{await onImport(incoming.archive,importMode);setIncoming(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Importing…':'Import'}</button></div></Modal>}
  {deleting&&<Modal title="Delete account?" onClose={()=>setDeleting(false)}><p>This permanently removes this local account and its records. Download a backup first if you need one.</p><label className="field"><span>Password</span><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="inline-error" role="alert">{error}</p>}<div className="modal-footer"><button className="button secondary" onClick={()=>setDeleting(false)}>Cancel</button><button className="button danger" disabled={busy||!password} onClick={async()=>{setBusy(true);try{await onDelete(password);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Delete permanently</button></div></Modal>}</>;
}
