import React from 'react';
import ReactDOM from 'react-dom/client';
import '@fontsource/inter/latin-400.css';
import '@fontsource/inter/latin-400-italic.css';
import '@fontsource/inter/latin-500.css';
import '@fontsource/inter/latin-600.css';
import '@fontsource/ibm-plex-mono/latin-400.css';
import App from './App';
import CloudGate from './components/CloudGate';
import { configureCloudTransport } from './lib/api';
import './styles.css';
import './components/MobileTimePicker.css';
import './components/DoseEditor.css';
import './components/symptoms.css';
import './components/FavoritePicker.css';
import './components/CloudGate.css';
const cloud=import.meta.env.DRUG_EDITION==='cloud';
if(cloud)configureCloudTransport(null);
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode>{cloud?<CloudGate/>:<App/>}</React.StrictMode>);
